[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/heretical-game.html"
  status = 200

[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json"
